In [40]:
import pandas as pd
import quandl
import math
import numpy as np
import sklearn

In [3]:
df = quandl.get('WIKI/GOOGL')

In [4]:
df.head()

Open    High     Low    Close      Volume  Ex-Dividend  \
Date                                                                   
2004-08-19  100.01  104.06   95.96  100.335  44659000.0          0.0   
2004-08-20  101.01  109.08  100.50  108.310  22834300.0          0.0   
2004-08-23  110.76  113.48  109.05  109.400  18256100.0          0.0   
2004-08-24  111.24  111.60  103.57  104.870  15247300.0          0.0   
2004-08-25  104.76  108.00  103.88  106.000   9188600.0          0.0   

            Split Ratio  Adj. Open  Adj. High   Adj. Low  Adj. Close  \
Date                                                                   
2004-08-19          1.0  50.159839  52.191109  48.128568   50.322842   
2004-08-20          1.0  50.661387  54.708881  50.405597   54.322689   
2004-08-23          1.0  55.551482  56.915693  54.693835   54.869377   
2004-08-24          1.0  55.792225  55.972783  51.945350   52.597363   
2004-08-25          1.0  52.542193  54.167209  52.100830   53.164113   

            Adj. Volume  
Date                     
2004-08-19   44659000.0  
2004-08-20   22834300.0  
2004-08-23   18256100.0  
2004-08-24   15247300.0  
2004-08-25    9188600.0

In [5]:
df = df[['Adj. Open','Adj. High','Adj. Low','Adj. Close','Adj. Volume']]

In [10]:
df['ML_PCT'] = (df['Adj. High'] - df['Adj. Low']) / df['Adj. Close'] * 100

In [11]:
df['PCT_change'] = (df['Adj. Close'] - df['Adj. Open']) / df['Adj. Open'] * 100

In [13]:
df = df[['Adj. Close','ML_PCT','PCT_change','Adj. Volume']]

In [14]:
df.head()

Adj. Close    ML_PCT  PCT_change  Adj. Volume
Date                                                     
2004-08-19   50.322842  8.072956    0.324968   44659000.0
2004-08-20   54.322689  7.921706    7.227007   22834300.0
2004-08-23   54.869377  4.049360   -1.227880   18256100.0
2004-08-24   52.597363  7.657099   -5.726357   15247300.0
2004-08-25   53.164113  3.886792    1.183658    9188600.0

In [15]:
forecast_col = 'Adj. Close'

In [17]:
df.fillna(-9999, inplace = True)

/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3790: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)


In [18]:
df.isnull().sum()

Adj. Close     0
ML_PCT         0
PCT_change     0
Adj. Volume    0
dtype: int64

In [26]:
forecast_cout = int(round(0.01*len(df)))

In [27]:
df['label'] = df[forecast_col].shift(-forecast_cout)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [28]:
df.dropna(inplace = True)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [29]:
df.head()

Adj. Close    ML_PCT  PCT_change  Adj. Volume      label
Date                                                                
2004-08-19   50.322842  8.072956    0.324968   44659000.0  69.639972
2004-08-20   54.322689  7.921706    7.227007   22834300.0  69.078238
2004-08-23   54.869377  4.049360   -1.227880   18256100.0  67.839414
2004-08-24   52.597363  7.657099   -5.726357   15247300.0  68.912727
2004-08-25   53.164113  3.886792    1.183658    9188600.0  70.668146

In [44]:
x = np.array(df.drop(['label'], 1))
print(x)
y = np.array(df['label'])

[[ 5.03228418e+01  8.07295560e+00  3.24967503e-01  4.46590000e+07]
 [ 5.43226889e+01  7.92170621e+00  7.22700723e+00  2.28343000e+07]
 [ 5.48693765e+01  4.04936015e+00 -1.22788010e+00  1.82561000e+07]
 ...
 [ 1.11920000e+03  1.79860615e+00 -7.29098295e-01  5.79888000e+06]
 [ 1.06876000e+03  5.45024140e+00 -2.89384977e+00  3.74246900e+06]
 [ 1.08443000e+03  5.29033686e+00  4.87920463e+00  3.73252700e+06]]


In [45]:
x = preprocessing.scale(x)
print(x)

[[-1.40952489  4.26408509  0.23064869  4.44854432]
 [-1.39350172  4.15577235  4.83357684  1.80916144]
 [-1.39131172  1.38270721 -0.8049359   1.25549414]
 ...
 [ 2.87233739 -0.22910314 -0.47230136 -0.25102705]
 [ 2.67027757  2.38590654 -1.9159609  -0.49972032]
 [ 2.73305071  2.27139567  3.26784162 -0.50092266]]


In [42]:
x_train, x_test, y_train, y_test = cross_validation.train_test_split(x, y, test_size = 0.2)

NameError: name 'cross_validation' is not defined

array([[-1.40952489,  4.26408509,  0.23064869,  4.44854432],
       [-1.39350172,  4.15577235,  4.83357684,  1.80916144],
       [-1.39131172,  1.38270721, -0.8049359 ,  1.25549414],
       ...,
       [ 2.87233739, -0.22910314, -0.47230136, -0.25102705],
       [ 2.67027757,  2.38590654, -1.9159609 , -0.49972032],
       [ 2.73305071,  2.27139567,  3.26784162, -0.50092266]])

In [64]:
import requests
from bs4 import BeautifulSoup

In [69]:
url = 'https://en.wikipedia.org/wiki/List_of_English_football_transfers_summer_2012'
html = requests.get(url).content
soup = BeautifulSoup(html, "lxml")
text = [element.text.replace('\n\n', '').replace('\n', ',') for element in soup.find_all('table',{'class':'wikitable sortable'})]
text

["Date,Name,Moving from,Moving to,Fee,1 February 2012, Joao Carlos Teixeira, Sporting CP,Liverpool,Undisclosed[1],2 February 2012, Ryan Nelsen,Blackburn Rovers,Tottenham Hotspur,Free[2],8 February 2012,Matthew Briggs,Fulham,Peterborough United,Loan,8 February 2012,Angus MacDonald,Reading,Torquay United,Loan[3],8 February 2012, Cristian Montaño,West Ham United,Notts County,Loan,8 February 2012,Brett Williams,Reading,Rotherham United,Loan,9 February 2012,Saido Berahino,West Bromwich Albion,Brentford,Loan,9 February 2012,Lawson D'Ath,Reading,Yeovil Town,Loan,9 February 2012,Ryan Dickson,Southampton,Leyton Orient,Loan,9 February 2012, George Elokobi,Wolverhampton Wanderers,Nottingham Forest,Loan[4],9 February 2012,Ben Gibson,Middlesbrough,York City,Loan[5],9 February 2012,Tom Parkes,Leicester City,Bristol Rovers,Loan,9 February 2012,Adam Thompson,Watford,Northampton Town,Loan,9 February 2012, Haris Vučkić,Newcastle United, Cardiff City,Loan,10 February 2012, Britt Assombalonga,Watford,Brai

In [78]:
url = 'https://en.wikipedia.org/wiki/List_of_English_football_transfers_summer_2012'
html = requests.get(url).content
soup = BeautifulSoup(html, "lxml")
my_table = soup.find('table',{'class':'wikitable sortable'})
names = []
for row in my_table.find_all('td'):
    try:
        names.append(row.find_all('a')[1].text)
    except IndexError:
        names.append('no')

print(names)

['no', 'no', 'Sporting CP', 'no', 'no', 'no', 'Ryan Nelsen', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'Cristian Montaño', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'George Elokobi', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'Haris Vučkić', 'no', 'Cardiff City', 'no', 'no', 'Britt Assombalonga', 'no', 'no', 'no', 'no', 'Habib Beye', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'Stephen McManus', 'no', 'no', 'no', 'no', 'Toni Silva', 'no', 'no', 'no', 'no', 'Bruno Uvini', 'São Paulo', 'no', 'no', 'no', 'David Cotterill', 'no', 'no', 'no', 'no', 'Barry Robson', 'no', 'Vancouver Whitecaps', 'no', 'no', 'Rene Gilmartin', 'no', 'no', 'no', 'no', 'Gai Assulin', 'no', 'no', 'no', 'no', 'Jamie Devitt', 'no', 'no', 'no', 'no', 'Abdul Razak', 'n

In [70]:
for i in text:
    ans = i.split(',')

In [74]:
name = []
for x in range(1, len(ans), 5):
    name.append(ans[x])
 

In [75]:
name

['Name',
 ' Joao Carlos Teixeira',
 ' Ryan Nelsen',
 'Matthew Briggs',
 'Angus MacDonald',
 ' Cristian Montaño',
 'Brett Williams',
 'Saido Berahino',
 "Lawson D'Ath",
 'Ryan Dickson',
 ' George Elokobi',
 'Ben Gibson',
 'Tom Parkes',
 'Adam Thompson',
 ' Haris Vučkić',
 ' Britt Assombalonga',
 ' Habib Beye',
 ' Francisco Júnior',
 'Lee Holmes',
 ' Stephen McManus',
 ' Toni Silva',
 ' Bruno Uvini',
 ' David Cotterill',
 ' Barry Robson',
 ' Rene Gilmartin',
 ' Gai Assulin',
 ' Jamie Devitt',
 ' Abdul Razak',
 'Olly Lee',
 'Freddie Sears',
 ' Jake Adelson',
 'Lateef Elford-Alliyu',
 'Miles Addison',
 'Michail Antonio',
 'Shaun Batt',
 'Tyrone Barnett',
 'Jack Butland',
 'Craig Eastmond',
 'Chris Hackett',
 ' Tomasz Kuszczak',
 ' Petros Skapetis',
 'Jonathan Franks',
 'Jonathan Grounds',
 ' Scott Allan',
 'Jonathan Bond',
 ' Erik Huseklepp',
 'Ben Reeves',
 ' Marcello Trotta',
 ' Andrei Arshavin',
 ' Trevor Carson',
 ' Mark Connolly',
 'Sean Davis',
 ' Michael Liddle',
 ' Mathieu Manset',

In [9]:
from selenium import webdriver 
from selenium.webdriver.common.by import By 
from selenium.webdriver.support.ui import WebDriverWait 
from selenium.webdriver.support import expected_conditions as EC 
from selenium.common.exceptions import TimeoutException

In [10]:
option = webdriver.ChromeOptions()
option.add_argument(' — incognito')
driver = webdriver.Chrome(executable_path = "/Users/grsanchez/Downloads/chrome", options=option)
driver.get('https://www.premierleague.com//players/2651/Petr-Cech/stats')

In [12]:
a = driver.find_elements_by_xpath('//ul[@id="mainContent"]')

[]

In [ ]:
.find_element_by_id()
.find_element_by_name()
.find_element_by_xpath()
.find_element_by_tag_name()
.find_element_by_class_name()
.find_element_by_css_selector()

In [53]:
from lxml import html
import requests
import pandas as pd
import numpy as np
import re

In [54]:
page = requests.get('https://www.premierleague.com/clubs?se=79')
tree = html.fromstring(page.content)

In [55]:
tree

<Element html at 0x122c723b8>

In [56]:
#Using the page's CSS classes, extract all links pointing to a team
linkLocation = tree.cssselect('.indexItem')
teamLinks = []

for i in range(0,20):
    
    #Find page link is going to.
    temp = linkLocation[i].attrib['href']
    
    #Add the link to the website domain.
    temp = "http://www.premierleague.com/" + temp
    
    #Change the link text so that it points to the squad list.
    temp = temp.replace("overview", "squad")
    teamLinks.append(temp)

In [57]:
linkLocation

[<Element a at 0x12232ea98>,
 <Element a at 0x12227a408>,
 <Element a at 0x12227a458>,
 <Element a at 0x12227a4a8>,
 <Element a at 0x12227a4f8>,
 <Element a at 0x12227a548>,
 <Element a at 0x12227a598>,
 <Element a at 0x12227a5e8>,
 <Element a at 0x12227a638>,
 <Element a at 0x12227a688>,
 <Element a at 0x12227a6d8>,
 <Element a at 0x12227a728>,
 <Element a at 0x12227a778>,
 <Element a at 0x12227a7c8>,
 <Element a at 0x12227a818>,
 <Element a at 0x12227a868>,
 <Element a at 0x12227a8b8>,
 <Element a at 0x12227a908>,
 <Element a at 0x12227a958>,
 <Element a at 0x12227a9a8>]

In [58]:
playerLink1 = []
playerLink2 = []

for i in range(len(teamLinks)):
    
    #Download the team page and process tml code.
    squadPage = requests.get(teamLinks[i])
    squadTree = html.fromstring(squadPage.content)
    
    #Extract the player links.
    playerLocation = squadTree.cssselect('.playerOverviewCard')

    #For each player link within the team page.
    for i in range(len(playerLocation)):
        
        #Save the link, complete with domain.
        playerLink1.append("http://www.premierleague.com/" + playerLocation[i].attrib['href'])
        
        #For the second link, change the page from player overview to stats
        playerLink2.append(playerLink1[i].replace("overview", "stats"))

In [59]:
playerLink1

['http://www.premierleague.com//players/2651/Petr-Cech/overview',
 'http://www.premierleague.com//players/4985/Bernd-Leno/overview',
 'http://www.premierleague.com//players/10542/Dejan-Iliev/overview',
 'http://www.premierleague.com//players/4474/Héctor-Bellerín/overview',
 'http://www.premierleague.com//players/4030/Laurent-Koscielny/overview',
 'http://www.premierleague.com//players/11575/Rob-Holding/overview',
 'http://www.premierleague.com//players/4472/Nacho-Monreal/overview',
 'http://www.premierleague.com//players/3869/Shkodran-Mustafi/overview',
 'http://www.premierleague.com//players/32638/Konstantinos-Mavropanos/overview',
 'http://www.premierleague.com//players/5368/Sead-Kolasinac/overview',
 'http://www.premierleague.com//players/5520/Stephan-Lichtsteiner/overview',
 'http://www.premierleague.com//players/4248/Carl-Jenkinson/overview',
 'http://www.premierleague.com//players/5093/Sokratis/overview',
 'http://www.premierleague.com//players/21958/Zech-Medley/overview',
 'http

In [60]:
playerLink2

['http://www.premierleague.com//players/2651/Petr-Cech/stats',
 'http://www.premierleague.com//players/4985/Bernd-Leno/stats',
 'http://www.premierleague.com//players/10542/Dejan-Iliev/stats',
 'http://www.premierleague.com//players/4474/Héctor-Bellerín/stats',
 'http://www.premierleague.com//players/4030/Laurent-Koscielny/stats',
 'http://www.premierleague.com//players/11575/Rob-Holding/stats',
 'http://www.premierleague.com//players/4472/Nacho-Monreal/stats',
 'http://www.premierleague.com//players/3869/Shkodran-Mustafi/stats',
 'http://www.premierleague.com//players/32638/Konstantinos-Mavropanos/stats',
 'http://www.premierleague.com//players/5368/Sead-Kolasinac/stats',
 'http://www.premierleague.com//players/5520/Stephan-Lichtsteiner/stats',
 'http://www.premierleague.com//players/4248/Carl-Jenkinson/stats',
 'http://www.premierleague.com//players/5093/Sokratis/stats',
 'http://www.premierleague.com//players/21958/Zech-Medley/stats',
 'http://www.premierleague.com//players/14433/Ju

In [63]:
Name = []
Team = []
Age = []
Apps = []
HeightCM = []
WeightKG = []

for i in range(len(playerLink1)):

    #...download and process the two pages collected earlier...
    playerPage1 = requests.get(playerLink1[i])
    playerTree1 = html.fromstring(playerPage1.content)
    playerPage2 = requests.get(playerLink2[i])
    playerTree2 = html.fromstring(playerPage2.content)

    #...find the relevant datapoint for each player, starting with name...
    tempName = str(playerTree1.cssselect('div.name')[0].text_content())
    
    #...and team, but if there isn't a team, return "BLANK"...
    try:
        tempTeam = str(playerTree1.cssselect('.table:nth-child(1) .long')[0].text_content())
    except IndexError:
        tempTeam = str("BLANK")
    
    #...and age, but if this isn't there, leave a blank 'no number' number...
    try:  
        tempAge = int(playerTree1.cssselect('.pdcol2 li:nth-child(1) .info')[0].text_content())
    except IndexError:
        tempAge = float('NaN')

    #...and appearances. This is a bit of a mess on the page, so tidy it first...
    try:
        tempApps = playerTree2.cssselect('.statsaves')[0].text_content()
        tempApps = int(re.search(r'\d+', tempApps).group())
    except IndexError:
        tempApps = float('NaN')

    #...and height. Needs tidying again...
    try:
        tempHeight = playerTree1.cssselect('.pdcol3 li:nth-child(1) .info')[0].text_content()
        tempHeight = int(re.search(r'\d+', tempHeight).group())
    except IndexError:
        tempHeight = float('NaN')

    #...and weight. Same with tidying and returning blanks if it isn't there
    try:
        tempWeight = playerTree1.cssselect('.pdcol3 li+ li .info')[0].text_content()
        tempWeight = int(re.search(r'\d+', tempWeight).group())
    except IndexError:
        tempWeight = float('NaN')
        
    Name.append(tempName)
    Team.append(tempTeam)
    Age.append(tempAge)
    Apps.append(tempApps)
    HeightCM.append(tempHeight)
    WeightKG.append(tempWeight)        

KeyboardInterrupt: 

In [ ]:
Age